name: securx
description: "A mobile security package enhancing app resilience with device integrity checks, secure communication, mobile privacy controls, and fraud prevention."
version: 0.0.2

homepage: https://github.com/Rgada28/securx
repository: https://github.com/Rgada28/securx
issue_tracker: https://github.com/Rgada28/securx/issues


license: BSD-3-Clause

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.35.7'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - security
  - securx
  - android
  - ios

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  plugin:
    platforms:
      android:
        package: com.security.securx.securx
        pluginClass: SecurxPlugin
      ios:
        pluginClass: SecurxPlugin
